[project]
name = "isaac-navigation"
authors = [
    {name = "Matteo Princisgh", email = "princisgh@gmail.com"},
    {name = "João Carvalho"}
    ]
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = [
    "pyastar2d>=1.1.0", # pending PR for python 3.11 support
    "loguru",
    "tensordict",
    "timm",
    "opencv-python",
    "matplotlib",
    "scikit-image",
    "numpy==1.26.0",
    "numba==0.59.1",
    "llvmlite==0.42.0",
    "networkx",
    "skan",
    "torch==2.7.0",
    "rsl-rl-lib==3.3.0",
    "efficientnet-pytorch",
    "warmup-scheduler",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
