[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "isaac-navigation"
authors = [
    {name = "Matteo Princisgh", email = "princisgh@gmail.com"},
    {name = "João Carvalho"}
    ]
version = "0.2.0"
requires-python = "==3.12.*"
dependencies = [
    "torch==2.10.0",
    "pyastar2d>=1.1.4",
    "loguru",
    "tensordict",
    "timm",
    "opencv-python",
    "matplotlib",
    "scikit-image",
    "networkx",
    "skan",
    "efficientnet-pytorch",
    "warmup-scheduler",
    "kornia",
    "ipywidgets",
    "ipympl",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "flake8",
    "pre-commit",
]

[tool.black]
line-length = 130

[tool.isort]
profile = "black"
